# [√]需要手动修改 [-]不推荐修改 [※]可选项，不影响系统运行
# ===================================================
# [√] Redis 节点连接配置
# ---------------------------------------------------
# Tips：使用脚手架检测连接 python main.py ping
# ===================================================
REDIS_NODE:
  host: "127.0.0.1"
  password: ""
  port: 8848
  db: 0

# ===================================================
# [√] 订阅池容量
# ---------------------------------------------------
# POOL_CAP 为订阅池容量，用于限制采集器的行为
# ---------------------------------------------------
# Tips: POOL_CAP >= 80% 不再添加新任务
# Tips: POOL_CAP >= 50% 开始优选待办任务
# Tips: POOL_CAP >= 0% 灌入数据集
# Tips: 个人使用推荐 POOL_CAP∈[5,8]
# ---------------------------------------------------
# Warning: POOL_CAP不能超过30，这会带来极大的性能开支
# ===================================================
POOL_CAP: 0


# ===================================================
# [-] 定时任务配置
# ---------------------------------------------------
# collector     |采集器
# decouple      |订阅池检测（heartbeat），清洗无效订阅
# ---------------------------------------------------
# interval      |任务间隔，单位秒
# Default: interval--(collector)--120s
# Default: interval--(decouple)--3600s
# ---------------------------------------------------
# Tips: 手动修改的 interval 不可小于默认值
# ===================================================
scheduler:
  collector:
    enable: true
    interval: 120
  decoupler:
    enable: true
    interval: 3600
